[build]
# Avoid linking Rust std's debug info, improving link times.
# TODO(strager): Only use this where the linker flag is supported.
# TODO(strager): Only use this for quick-build-incremental and
# quick-build-nonincremental.
rustflags = ["-Clink-args=-Wl,-s"]
